# Make sure this is consistent with mysql part of docker-compose.yml
FLASK_SECRET_KEY: SOME_RANDOM_SECRET_KEY

DATABASE_CONN: postgresql://story:story@postgres:5432/story
REDIS_URL: redis://redis:6379/0
ELASTICSEARCH_HOST: elasticsearch:9200
# Uncomment for email
# EMAILER_CONN: dockerhostforward

# HEIMDALL AUTH
AUTH_BACKEND: 'auth_plugin.heimdall_auth'
OIDC_CLIENT_ID: 'dataos_generic'
OIDC_CLIENT_SECRET: '665CAF977DA1ED77456B7CD3F3FD4'
DATAOS_BASE_URL: https://main-lamb.dataos.app/
PUBLIC_URL: http://127.0.0.1:3000

# MINERVA
MINERVA_QUERY_URL: https://tcp.main-lamb.dataos.app:7432

# Email Notifications
MAIL_SERVER: smtp.mailgun.org
MAIL_PORT: 587
MAIL_USE_TLS: true
MAIL_USE_SSL: true
MAIL_USERNAME: postmaster@dataos.animesh.org
MAIL_PASSWORD: e43c55a4ec1bca1a1b4ad4e7ba50a1e5-f7d0b107-e3325356
MAIL_DEFAULT_SENDER: "DataOS Querybook <querybook@dataos.animesh.org>"
