DATABASE_CONN: postgresql://story:story@postgres:5432/story
REDIS_URL: redis://redis:6379/0
ELASTICSEARCH_HOST: elasticsearch:9200

# HEIMDALL AUTH
AUTH_BACKEND: 'auth_plugin.heimdall_auth'
OIDC_CLIENT_ID: 'dataos_generic'
OIDC_CLIENT_SECRET: '665CAF977DA1ED77456B7CD3F3FD4'
DATAOS_BASE_URL: https://main-lamb.dataos.app/
DATAOS_APIKEY: YXRsYXNfNDBkMTMwMDY4NTM4OTM3ZWIwY2ZiOGI0YWIyMjcyOWIuMWY0ZmVmZDUtODliMi00ZTkyLWJhZGYtODdlYzY0YmQ4NjQ2
PUBLIC_URL: http://127.0.0.1:10001

# MINERVA
MINERVA_QUERY_URL: https://tcp.main-lamb.dataos.app:7432

# Email Notifications
MAIL_SERVER: smtp.mailgun.org
MAIL_PORT: 587
MAIL_USE_TLS: true
MAIL_USE_SSL: false
MAIL_USERNAME: querybook@mail.dataos.io
MAIL_DEFAULT_SENDER: "DataOS Querybook <querybook@mail.dataos.io>"
# Must be provided in the Env
# MAIL_PASSWORD: "*** REDACTED ***"
