# Make sure this is consistent with mysql part of docker-compose.yml
FLASK_SECRET_KEY: SOME_RANDOM_SECRET_KEY

DATABASE_CONN: postgresql://story:story@postgres:5432/story
REDIS_URL: redis://redis:6379/0
ELASTICSEARCH_HOST: elasticsearch:9200
# Uncomment for email
# EMAILER_CONN: dockerhostforward
