minerva_connection_regex = r"^(http|https):\/\/([\w.-]+(?:\:\d+)?(?:,[\w.-]+(?:\:\d+)?)*)(\/\w+)?(\/\w+)?(\?[\w.-]+=[\w.-]+(?:&[\w.-]+=[\w.-]+)*)?$"
minerva_cluster_regex = r"^[A-Za-z0-9]+$"
heimdall_apikey_regex = r"^[A-Za-z0-9=]+$"
minerva_language = "Minerva"
minerva_executor_name = "Minerva"
